apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo
  name: postgres-data-pvc
spec:
  # We will be using the default dynamic storage provisioner # storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
